apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-production
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
        env: production
        version: v1
    spec:
      containers:
      - name: hello-world 
        image: quay.io/jordan_cooks/hello-world-instrumented:v1
        ports:
        - name: web
          containerPort: 5000
        - name: metrics
          containerPort: 8000
